package modules

type dgContinent struct {
	iso2, iso3, name string
}

type dgCountry struct {
	officialName  string
	iso2          string
	iso3          string
	isoNumeric    int
	currencyCode  string
	currencyName  string
	englishFormal string
	englishShort  string
	capital       string
	continent     string
	languages     string
	regionCode    int
	regionName    string
	subRegionCode int
	subRegionName string
	tld           string
	isIndependent string
}

type dgCity struct {
	name, country, subcountry, iso3 string
	geonameid                       int
}

type dgStreet struct {
	streetname string
}

type dgTitle struct {
	name                              string
	bho, onlyman, alsofem, norder, id int
}

type dgPopulationRow struct {
	countryname, iso3, seriesname, seriescode string
	y2019, y2020, y2021                       int64
}

var dgContinents = []dgContinent{
	{"AF", "AFR", "Africa"},
	{"AN", "ANT", "Antarctica"},
	{"AS", "ASI", "Asia"},
	{"EU", "EUR", "Europe"},
	{"NA", "NAM", "North America"},
	{"OC", "OCE", "Oceania"},
	{"SA", "SAM", "South America"},
}

var dgCountries = []dgCountry{
	{"Republic of Albania", "AL", "ALB", 8, "ALL", "Albanian lek", "Republic of Albania", "Albania", "Tirana", "Europe", "sq", 150, "Europe", 39, "Southern Europe", ".al", "Yes"},
	{"Principality of Andorra", "AD", "AND", 20, "EUR", "Euro", "Principality of Andorra", "Andorra", "Andorra la Vella", "Europe", "ca", 150, "Europe", 39, "Southern Europe", ".ad", "Yes"},
	{"Republic of Austria", "AT", "AUT", 40, "EUR", "Euro", "Republic of Austria", "Austria", "Vienna", "Europe", "de", 150, "Europe", 155, "Western Europe", ".at", "Yes"},
	{"Republic of Belarus", "BY", "BLR", 112, "BYR", "Belarusian ruble", "Republic of Belarus", "Belarus", "Minsk", "Europe", "be,ru", 150, "Europe", 151, "Eastern Europe", ".by", "Yes"},
	{"Kingdom of Belgium", "BE", "BEL", 56, "EUR", "Euro", "Kingdom of Belgium", "Belgium", "Brussels", "Europe", "nl,fr,de", 150, "Europe", 155, "Western Europe", ".be", "Yes"},
	{"Bosnia and Herzegovina", "BA", "BIH", 70, "BAM", "Convertible mark", "Bosnia and Herzegovina", "Bosnia and Herzegovina", "Sarajevo", "Europe", "bs,hr,sr", 150, "Europe", 39, "Southern Europe", ".ba", "Yes"},
	{"Republic of Bulgaria", "BG", "BGR", 100, "BGN", "Bulgarian lev", "Republic of Bulgaria", "Bulgaria", "Sofia", "Europe", "bg", 150, "Europe", 151, "Eastern Europe", ".bg", "Yes"},
	{"Republic of Croatia", "HR", "HRV", 191, "HRK", "Croatian kuna", "Republic of Croatia", "Croatia", "Zagreb", "Europe", "hr", 150, "Europe", 39, "Southern Europe", ".hr", "Yes"},
	{"Republic of Cyprus", "CY", "CYP", 196, "EUR", "Euro", "Republic of Cyprus", "Cyprus", "Nicosia", "Europe", "el,tr", 150, "Europe", 145, "Western Asia", ".cy", "Yes"},
	{"Czech Republic", "CZ", "CZE", 203, "CZK", "Czech koruna", "Czech Republic", "Czech Republic", "Prague", "Europe", "cs,sk", 150, "Europe", 151, "Eastern Europe", ".cz", "Yes"},
	{"Kingdom of Denmark", "DK", "DNK", 208, "DKK", "Danish krone", "Kingdom of Denmark", "Denmark", "Copenhagen", "Europe", "da", 150, "Europe", 154, "Northern Europe", ".dk", "Yes"},
	{"Republic of Estonia", "EE", "EST", 233, "EUR", "Euro", "Republic of Estonia", "Estonia", "Tallinn", "Europe", "et", 150, "Europe", 154, "Northern Europe", ".ee", "Yes"},
	{"Republic of Finland", "FI", "FIN", 246, "EUR", "Euro", "Republic of Finland", "Finland", "Helsinki", "Europe", "fi,sv", 150, "Europe", 154, "Northern Europe", ".fi", "Yes"},
	{"French Republic", "FR", "FRA", 250, "EUR", "Euro", "French Republic", "France", "Paris", "Europe", "fr", 150, "Europe", 155, "Western Europe", ".fr", "Yes"},
	{"Federal Republic of Germany", "DE", "DEU", 276, "EUR", "Euro", "Federal Republic of Germany", "Germany", "Berlin", "Europe", "de", 150, "Europe", 155, "Western Europe", ".de", "Yes"},
	{"Hellenic Republic", "GR", "GRC", 300, "EUR", "Euro", "Hellenic Republic", "Greece", "Athens", "Europe", "el", 150, "Europe", 39, "Southern Europe", ".gr", "Yes"},
	{"Republic of Hungary", "HU", "HUN", 348, "HUF", "Hungarian forint", "Republic of Hungary", "Hungary", "Budapest", "Europe", "hu", 150, "Europe", 151, "Eastern Europe", ".hu", "Yes"},
	{"Republic of Iceland", "IS", "ISL", 352, "ISK", "Icelandic króna", "Republic of Iceland", "Iceland", "Reykjavik", "Europe", "is", 150, "Europe", 154, "Northern Europe", ".is", "Yes"},
	{"Ireland", "IE", "IRL", 372, "EUR", "Euro", "Ireland", "Ireland", "Dublin", "Europe", "en,ga", 150, "Europe", 154, "Northern Europe", ".ie", "Yes"},
	{"Italian Republic", "IT", "ITA", 380, "EUR", "Euro", "Italian Republic", "Italy", "Rome", "Europe", "it", 150, "Europe", 39, "Southern Europe", ".it", "Yes"},
	{"Republic of Kosovo", "XK", "XKX", 0, "EUR", "Euro", "Republic of Kosovo", "Kosovo", "Pristina", "Europe", "sq,sr", 150, "Europe", 39, "Southern Europe", ".xk", "Yes"},
	{"Republic of Latvia", "LV", "LVA", 428, "EUR", "Euro", "Republic of Latvia", "Latvia", "Riga", "Europe", "lv", 150, "Europe", 154, "Northern Europe", ".lv", "Yes"},
	{"Principality of Liechtenstein", "LI", "LIE", 438, "CHF", "Swiss franc", "Principality of Liechtenstein", "Liechtenstein", "Vaduz", "Europe", "de", 150, "Europe", 155, "Western Europe", ".li", "Yes"},
	{"Republic of Lithuania", "LT", "LTU", 440, "EUR", "Euro", "Republic of Lithuania", "Lithuania", "Vilnius", "Europe", "lt", 150, "Europe", 154, "Northern Europe", ".lt", "Yes"},
	{"Grand Duchy of Luxembourg", "LU", "LUX", 442, "EUR", "Euro", "Grand Duchy of Luxembourg", "Luxembourg", "Luxembourg", "Europe", "lb,fr,de", 150, "Europe", 155, "Western Europe", ".lu", "Yes"},
	{"Republic of Malta", "MT", "MLT", 470, "EUR", "Euro", "Republic of Malta", "Malta", "Valletta", "Europe", "mt,en", 150, "Europe", 39, "Southern Europe", ".mt", "Yes"},
	{"Republic of Moldova", "MD", "MDA", 498, "MDL", "Moldovan leu", "Republic of Moldova", "Moldova", "Chisinau", "Europe", "ro", 150, "Europe", 151, "Eastern Europe", ".md", "Yes"},
	{"Principality of Monaco", "MC", "MCO", 492, "EUR", "Euro", "Principality of Monaco", "Monaco", "Monaco", "Europe", "fr", 150, "Europe", 155, "Western Europe", ".mc", "Yes"},
	{"Montenegro", "ME", "MNE", 499, "EUR", "Euro", "Montenegro", "Montenegro", "Podgorica", "Europe", "sr", 150, "Europe", 39, "Southern Europe", ".me", "Yes"},
	{"Kingdom of the Netherlands", "NL", "NLD", 528, "EUR", "Euro", "Kingdom of the Netherlands", "Netherlands", "Amsterdam", "Europe", "nl", 150, "Europe", 155, "Western Europe", ".nl", "Yes"},
	{"Republic of North Macedonia", "MK", "MKD", 807, "MKD", "Macedonian denar", "Republic of North Macedonia", "North Macedonia", "Skopje", "Europe", "mk,sq", 150, "Europe", 39, "Southern Europe", ".mk", "Yes"},
	{"Kingdom of Norway", "NO", "NOR", 578, "NOK", "Norwegian krone", "Kingdom of Norway", "Norway", "Oslo", "Europe", "no,nb,nn", 150, "Europe", 154, "Northern Europe", ".no", "Yes"},
	{"Republic of Poland", "PL", "POL", 616, "PLN", "Polish zloty", "Republic of Poland", "Poland", "Warsaw", "Europe", "pl", 150, "Europe", 151, "Eastern Europe", ".pl", "Yes"},
	{"Portuguese Republic", "PT", "PRT", 620, "EUR", "Euro", "Portuguese Republic", "Portugal", "Lisbon", "Europe", "pt", 150, "Europe", 39, "Southern Europe", ".pt", "Yes"},
	{"Romania", "RO", "ROU", 642, "RON", "Romanian leu", "Romania", "Romania", "Bucharest", "Europe", "ro", 150, "Europe", 151, "Eastern Europe", ".ro", "Yes"},
	{"Republic of San Marino", "SM", "SMR", 674, "EUR", "Euro", "Republic of San Marino", "San Marino", "San Marino", "Europe", "it", 150, "Europe", 39, "Southern Europe", ".sm", "Yes"},
	{"Republic of Serbia", "RS", "SRB", 688, "RSD", "Serbian dinar", "Republic of Serbia", "Serbia", "Belgrade", "Europe", "sr", 150, "Europe", 39, "Southern Europe", ".rs", "Yes"},
	{"Slovak Republic", "SK", "SVK", 703, "EUR", "Euro", "Slovak Republic", "Slovakia", "Bratislava", "Europe", "sk", 150, "Europe", 151, "Eastern Europe", ".sk", "Yes"},
	{"Republic of Slovenia", "SI", "SVN", 705, "EUR", "Euro", "Republic of Slovenia", "Slovenia", "Ljubljana", "Europe", "sl", 150, "Europe", 39, "Southern Europe", ".si", "Yes"},
	{"Kingdom of Spain", "ES", "ESP", 724, "EUR", "Euro", "Kingdom of Spain", "Spain", "Madrid", "Europe", "es", 150, "Europe", 39, "Southern Europe", ".es", "Yes"},
	{"Kingdom of Sweden", "SE", "SWE", 752, "SEK", "Swedish krona", "Kingdom of Sweden", "Sweden", "Stockholm", "Europe", "sv", 150, "Europe", 154, "Northern Europe", ".se", "Yes"},
	{"Swiss Confederation", "CH", "CHE", 756, "CHF", "Swiss franc", "Swiss Confederation", "Switzerland", "Bern", "Europe", "de,fr,it,rm", 150, "Europe", 155, "Western Europe", ".ch", "Yes"},
	{"Ukraine", "UA", "UKR", 804, "UAH", "Ukrainian hryvnia", "Ukraine", "Ukraine", "Kyiv", "Europe", "uk", 150, "Europe", 151, "Eastern Europe", ".ua", "Yes"},
	{"United Kingdom of Great Britain and Northern Ireland", "GB", "GBR", 826, "GBP", "Pound sterling", "United Kingdom of Great Britain and Northern Ireland", "United Kingdom", "London", "Europe", "en", 150, "Europe", 154, "Northern Europe", ".gb", "Yes"},
}

var dgCities = []dgCity{
	// Italy - 60 cities
	{"Roma", "Italy", "Lazio", "ITA", 3169070},
	{"Milano", "Italy", "Lombardia", "ITA", 3173435},
	{"Napoli", "Italy", "Campania", "ITA", 3172394},
	{"Torino", "Italy", "Piemonte", "ITA", 3165524},
	{"Palermo", "Italy", "Sicilia", "ITA", 2523920},
	{"Genova", "Italy", "Liguria", "ITA", 3176219},
	{"Bologna", "Italy", "Emilia-Romagna", "ITA", 3181928},
	{"Firenze", "Italy", "Toscana", "ITA", 3176959},
	{"Bari", "Italy", "Puglia", "ITA", 3181048},
	{"Catania", "Italy", "Sicilia", "ITA", 2525068},
	{"Venezia", "Italy", "Veneto", "ITA", 3164603},
	{"Verona", "Italy", "Veneto", "ITA", 3164527},
	{"Messina", "Italy", "Sicilia", "ITA", 2524469},
	{"Padova", "Italy", "Veneto", "ITA", 3171366},
	{"Trieste", "Italy", "Friuli-Venezia Giulia", "ITA", 3165185},
	{"Brescia", "Italy", "Lombardia", "ITA", 3182163},
	{"Taranto", "Italy", "Puglia", "ITA", 3165986},
	{"Prato", "Italy", "Toscana", "ITA", 3170071},
	{"Reggio Calabria", "Italy", "Calabria", "ITA", 2523630},
	{"Modena", "Italy", "Emilia-Romagna", "ITA", 3173332},
	{"Reggio Emilia", "Italy", "Emilia-Romagna", "ITA", 3170027},
	{"Perugia", "Italy", "Umbria", "ITA", 3171228},
	{"Livorno", "Italy", "Toscana", "ITA", 3174735},
	{"Ravenna", "Italy", "Emilia-Romagna", "ITA", 3169893},
	{"Cagliari", "Italy", "Sardegna", "ITA", 2525751},
	{"Foggia", "Italy", "Puglia", "ITA", 3177090},
	{"Rimini", "Italy", "Emilia-Romagna", "ITA", 3169361},
	{"Salerno", "Italy", "Campania", "ITA", 3168674},
	{"Ferrara", "Italy", "Emilia-Romagna", "ITA", 3177090},
	{"Sassari", "Italy", "Sardegna", "ITA", 2523743},
	{"Latina", "Italy", "Lazio", "ITA", 3175179},
	{"Giugliano in Campania", "Italy", "Campania", "ITA", 3176655},
	{"Monza", "Italy", "Lombardia", "ITA", 3172523},
	{"Siracusa", "Italy", "Sicilia", "ITA", 2523083},
	{"Bergamo", "Italy", "Lombardia", "ITA", 3182164},
	{"Pescara", "Italy", "Abruzzo", "ITA", 3171341},
	{"Trento", "Italy", "Trentino-Alto Adige", "ITA", 3165243},
	{"Forlì", "Italy", "Emilia-Romagna", "ITA", 3177073},
	{"Vicenza", "Italy", "Veneto", "ITA", 3164529},
	{"Terni", "Italy", "Umbria", "ITA", 3165762},
	{"Bolzano", "Italy", "Trentino-Alto Adige", "ITA", 3181913},
	{"Novara", "Italy", "Piemonte", "ITA", 3172298},
	{"Piacenza", "Italy", "Emilia-Romagna", "ITA", 3171359},
	{"Ancona", "Italy", "Marche", "ITA", 3183088},
	{"Andria", "Italy", "Puglia", "ITA", 3183065},
	{"Arezzo", "Italy", "Toscana", "ITA", 3182996},
	{"Udine", "Italy", "Friuli-Venezia Giulia", "ITA", 3165055},
	{"Cesena", "Italy", "Emilia-Romagna", "ITA", 3179435},
	{"Lecce", "Italy", "Puglia", "ITA", 3175117},
	{"Barletta", "Italy", "Puglia", "ITA", 3182705},
	{"Catanzaro", "Italy", "Calabria", "ITA", 2525417},
	{"La Spezia", "Italy", "Liguria", "ITA", 3175312},
	{"Torre del Greco", "Italy", "Campania", "ITA", 3165608},
	{"Como", "Italy", "Lombardia", "ITA", 3178229},
	{"Alessandria", "Italy", "Piemonte", "ITA", 3183264},
	{"Pesaro", "Italy", "Marche", "ITA", 3171365},
	{"Macerata", "Italy", "Marche", "ITA", 3174548},
	{"Pistoia", "Italy", "Toscana", "ITA", 3170741},
	{"Lucca", "Italy", "Toscana", "ITA", 3174621},
	{"Cosenza", "Italy", "Calabria", "ITA", 2523812},

	// France - 50 cities
	{"Paris", "France", "Île-de-France", "FRA", 2988507},
	{"Marseille", "France", "Provence-Alpes-Côte d'Azur", "FRA", 2995469},
	{"Lyon", "France", "Auvergne-Rhône-Alpes", "FRA", 2996944},
	{"Toulouse", "France", "Occitanie", "FRA", 2972315},
	{"Nice", "France", "Provence-Alpes-Côte d'Azur", "FRA", 2990440},
	{"Nantes", "France", "Pays de la Loire", "FRA", 2990969},
	{"Montpellier", "France", "Occitanie", "FRA", 2992166},
	{"Strasbourg", "France", "Grand Est", "FRA", 2973783},
	{"Bordeaux", "France", "Nouvelle-Aquitaine", "FRA", 3031582},
	{"Lille", "France", "Hauts-de-France", "FRA", 2998324},
	{"Rennes", "France", "Bretagne", "FRA", 2983990},
	{"Reims", "France", "Grand Est", "FRA", 2984114},
	{"Saint-Étienne", "France", "Auvergne-Rhône-Alpes", "FRA", 2980291},
	{"Toulon", "France", "Provence-Alpes-Côte d'Azur", "FRA", 2972328},
	{"Le Havre", "France", "Normandie", "FRA", 3003796},
	{"Grenoble", "France", "Auvergne-Rhône-Alpes", "FRA", 3014728},
	{"Dijon", "France", "Bourgogne-Franche-Comté", "FRA", 3021372},
	{"Nîmes", "France", "Occitanie", "FRA", 2990440},
	{"Aix-en-Provence", "France", "Provence-Alpes-Côte d'Azur", "FRA", 3038354},
	{"Brest", "France", "Bretagne", "FRA", 3031155},
	{"Le Mans", "France", "Pays de la Loire", "FRA", 3003468},
	{"Amiens", "France", "Hauts-de-France", "FRA", 3038354},
	{"Tours", "France", "Centre-Val de Loire", "FRA", 2972315},
	{"Limoges", "France", "Nouvelle-Aquitaine", "FRA", 2998801},
	{"Clermont-Ferrand", "France", "Auvergne-Rhône-Alpes", "FRA", 3024162},
	{"Villeurbanne", "France", "Auvergne-Rhône-Alpes", "FRA", 2968773},
	{"Besançon", "France", "Bourgogne-Franche-Comté", "FRA", 3032932},
	{"Metz", "France", "Grand Est", "FRA", 2991214},
	{"Perpignan", "France", "Occitanie", "FRA", 2988222},
	{"Orléans", "France", "Centre-Val de Loire", "FRA", 2989317},
	{"Mulhouse", "France", "Grand Est", "FRA", 2992097},
	{"Rouen", "France", "Normandie", "FRA", 2982681},
	{"Boulogne-Billancourt", "France", "Île-de-France", "FRA", 3031073},
	{"Caen", "France", "Normandie", "FRA", 3028808},
	{"Nancy", "France", "Grand Est", "FRA", 2990440},
	{"Argenteuil", "France", "Île-de-France", "FRA", 3038354},
	{"Saint-Denis", "France", "Île-de-France", "FRA", 2980290},
	{"Montreuil", "France", "Île-de-France", "FRA", 2992348},
	{"Tourcoing", "France", "Hauts-de-France", "FRA", 2972328},
	{"Roubaix", "France", "Hauts-de-France", "FRA", 2982547},
	{"Avignon", "France", "Provence-Alpes-Côte d'Azur", "FRA", 3038354},
	{"Nanterre", "France", "Île-de-France", "FRA", 2990440},
	{"Créteil", "France", "Île-de-France", "FRA", 3021372},
	{"Dunkerque", "France", "Hauts-de-France", "FRA", 3021372},
	{"Poitiers", "France", "Nouvelle-Aquitaine", "FRA", 2986495},
	{"Versailles", "France", "Île-de-France", "FRA", 2969326},
	{"Colombes", "France", "Île-de-France", "FRA", 3025491},
	{"Pau", "France", "Nouvelle-Aquitaine", "FRA", 2988734},
	{"Calais", "France", "Hauts-de-France", "FRA", 3028808},
	{"Vitry-sur-Seine", "France", "Île-de-France", "FRA", 2968773},

	// Germany - 50 cities
	{"Berlin", "Germany", "Berlin", "DEU", 2950159},
	{"Hamburg", "Germany", "Hamburg", "DEU", 2911298},
	{"München", "Germany", "Bayern", "DEU", 2867714},
	{"Köln", "Germany", "Nordrhein-Westfalen", "DEU", 2886242},
	{"Frankfurt am Main", "Germany", "Hessen", "DEU", 2925533},
	{"Stuttgart", "Germany", "Baden-Württemberg", "DEU", 2825297},
	{"Düsseldorf", "Germany", "Nordrhein-Westfalen", "DEU", 2934246},
	{"Leipzig", "Germany", "Sachsen", "DEU", 2879139},
	{"Dortmund", "Germany", "Nordrhein-Westfalen", "DEU", 2935517},
	{"Essen", "Germany", "Nordrhein-Westfalen", "DEU", 2928810},
	{"Bremen", "Germany", "Bremen", "DEU", 2944388},
	{"Dresden", "Germany", "Sachsen", "DEU", 2935022},
	{"Hannover", "Germany", "Niedersachsen", "DEU", 2910831},
	{"Nürnberg", "Germany", "Bayern", "DEU", 2861650},
	{"Duisburg", "Germany", "Nordrhein-Westfalen", "DEU", 2934091},
	{"Bochum", "Germany", "Nordrhein-Westfalen", "DEU", 2947416},
	{"Wuppertal", "Germany", "Nordrhein-Westfalen", "DEU", 2806491},
	{"Bielefeld", "Germany", "Nordrhein-Westfalen", "DEU", 2949186},
	{"Bonn", "Germany", "Nordrhein-Westfalen", "DEU", 2946447},
	{"Münster", "Germany", "Nordrhein-Westfalen", "DEU", 2867543},
	{"Karlsruhe", "Germany", "Baden-Württemberg", "DEU", 2892794},
	{"Mannheim", "Germany", "Baden-Württemberg", "DEU", 2873891},
	{"Augsburg", "Germany", "Bayern", "DEU", 2954172},
	{"Wiesbaden", "Germany", "Hessen", "DEU", 2809346},
	{"Gelsenkirchen", "Germany", "Nordrhein-Westfalen", "DEU", 2921232},
	{"Mönchengladbach", "Germany", "Nordrhein-Westfalen", "DEU", 2871831},
	{"Braunschweig", "Germany", "Niedersachsen", "DEU", 2945024},
	{"Chemnitz", "Germany", "Sachsen", "DEU", 3078610},
	{"Kiel", "Germany", "Schleswig-Holstein", "DEU", 2891122},
	{"Aachen", "Germany", "Nordrhein-Westfalen", "DEU", 3247449},
	{"Halle", "Germany", "Sachsen-Anhalt", "DEU", 2911522},
	{"Magdeburg", "Germany", "Sachsen-Anhalt", "DEU", 2874545},
	{"Freiburg im Breisgau", "Germany", "Baden-Württemberg", "DEU", 2925177},
	{"Krefeld", "Germany", "Nordrhein-Westfalen", "DEU", 2883455},
	{"Lübeck", "Germany", "Schleswig-Holstein", "DEU", 2875601},
	{"Oberhausen", "Germany", "Nordrhein-Westfalen", "DEU", 2859927},
	{"Erfurt", "Germany", "Thüringen", "DEU", 2928751},
	{"Rostock", "Germany", "Mecklenburg-Vorpommern", "DEU", 2844588},
	{"Mainz", "Germany", "Rheinland-Pfalz", "DEU", 2874225},
	{"Kassel", "Germany", "Hessen", "DEU", 2891674},
	{"Hagen", "Germany", "Nordrhein-Westfalen", "DEU", 2911477},
	{"Hamm", "Germany", "Nordrhein-Westfalen", "DEU", 2911303},
	{"Saarbrücken", "Germany", "Saarland", "DEU", 2842166},
	{"Mülheim an der Ruhr", "Germany", "Nordrhein-Westfalen", "DEU", 2867268},
	{"Potsdam", "Germany", "Brandenburg", "DEU", 2852458},
	{"Ludwigshafen", "Germany", "Rheinland-Pfalz", "DEU", 2876182},
	{"Oldenburg", "Germany", "Niedersachsen", "DEU", 2860917},
	{"Leverkusen", "Germany", "Nordrhein-Westfalen", "DEU", 2878234},
	{"Osnabrück", "Germany", "Niedersachsen", "DEU", 2859687},
	{"Solingen", "Germany", "Nordrhein-Westfalen", "DEU", 2826127},

	// Spain - 40 cities
	{"Madrid", "Spain", "Comunidad de Madrid", "ESP", 3117735},
	{"Barcelona", "Spain", "Cataluña", "ESP", 3128760},
	{"Valencia", "Spain", "Comunidad Valenciana", "ESP", 2509954},
	{"Sevilla", "Spain", "Andalucía", "ESP", 2510911},
	{"Zaragoza", "Spain", "Aragón", "ESP", 2509830},
	{"Málaga", "Spain", "Andalucía", "ESP", 2514256},
	{"Murcia", "Spain", "Región de Murcia", "ESP", 2513413},
	{"Palma", "Spain", "Islas Baleares", "ESP", 2512989},
	{"Las Palmas de Gran Canaria", "Spain", "Canarias", "ESP", 2515270},
	{"Bilbao", "Spain", "País Vasco", "ESP", 3128026},
	{"Alicante", "Spain", "Comunidad Valenciana", "ESP", 2521978},
	{"Córdoba", "Spain", "Andalucía", "ESP", 2519240},
	{"Valladolid", "Spain", "Castilla y León", "ESP", 3106672},
	{"Vigo", "Spain", "Galicia", "ESP", 3104499},
	{"Gijón", "Spain", "Asturias", "ESP", 3121456},
	{"Hospitalet de Llobregat", "Spain", "Cataluña", "ESP", 3120581},
	{"A Coruña", "Spain", "Galicia", "ESP", 3109642},
	{"Granada", "Spain", "Andalucía", "ESP", 3578760},
	{"Vitoria-Gasteiz", "Spain", "País Vasco", "ESP", 3104500},
	{"Elche", "Spain", "Comunidad Valenciana", "ESP", 2518536},
	{"Oviedo", "Spain", "Asturias", "ESP", 3113376},
	{"Badalona", "Spain", "Cataluña", "ESP", 3130081},
	{"Cartagena", "Spain", "Región de Murcia", "ESP", 2520611},
	{"Terrassa", "Spain", "Cataluña", "ESP", 3107961},
	{"Jerez de la Frontera", "Spain", "Andalucía", "ESP", 2517479},
	{"Sabadell", "Spain", "Cataluña", "ESP", 3110685},
	{"Santa Cruz de Tenerife", "Spain", "Canarias", "ESP", 2511401},
	{"Pamplona", "Spain", "Comunidad Foral de Navarra", "ESP", 3114709},
	{"Almería", "Spain", "Andalucía", "ESP", 2521886},
	{"Fuenlabrada", "Spain", "Comunidad de Madrid", "ESP", 3121299},
	{"Leganés", "Spain", "Comunidad de Madrid", "ESP", 3118464},
	{"San Sebastián", "Spain", "País Vasco", "ESP", 3110044},
	{"Getafe", "Spain", "Comunidad de Madrid", "ESP", 3121438},
	{"Burgos", "Spain", "Castilla y León", "ESP", 3125843},
	{"Castellón de la Plana", "Spain", "Comunidad Valenciana", "ESP", 2520591},
	{"Alcalá de Henares", "Spain", "Comunidad de Madrid", "ESP", 3130077},
	{"Albacete", "Spain", "Castilla-La Mancha", "ESP", 2522119},
	{"Logroño", "Spain", "La Rioja", "ESP", 3120375},
	{"Badajoz", "Spain", "Extremadura", "ESP", 3129135},
	{"Salamanca", "Spain", "Castilla y León", "ESP", 3111315},

	// UK - 40 cities
	{"London", "United Kingdom", "England", "GBR", 2643743},
	{"Birmingham", "United Kingdom", "England", "GBR", 2655603},
	{"Leeds", "United Kingdom", "England", "GBR", 2644688},
	{"Glasgow", "United Kingdom", "Scotland", "GBR", 2648579},
	{"Sheffield", "United Kingdom", "England", "GBR", 2637909},
	{"Bradford", "United Kingdom", "England", "GBR", 2654993},
	{"Manchester", "United Kingdom", "England", "GBR", 2643123},
	{"Edinburgh", "United Kingdom", "Scotland", "GBR", 2650225},
	{"Liverpool", "United Kingdom", "England", "GBR", 2644210},
	{"Bristol", "United Kingdom", "England", "GBR", 2654675},
	{"Cardiff", "United Kingdom", "Wales", "GBR", 2653822},
	{"Coventry", "United Kingdom", "England", "GBR", 2652221},
	{"Nottingham", "United Kingdom", "England", "GBR", 2641170},
	{"Leicester", "United Kingdom", "England", "GBR", 2644668},
	{"Sunderland", "United Kingdom", "England", "GBR", 2636741},
	{"Belfast", "United Kingdom", "Northern Ireland", "GBR", 2655984},
	{"Newcastle upon Tyne", "United Kingdom", "England", "GBR", 2641673},
	{"Brighton", "United Kingdom", "England", "GBR", 2654710},
	{"Hull", "United Kingdom", "England", "GBR", 2646141},
	{"Plymouth", "United Kingdom", "England", "GBR", 2640092},
	{"Stoke-on-Trent", "United Kingdom", "England", "GBR", 2636638},
	{"Wolverhampton", "United Kingdom", "England", "GBR", 2633563},
	{"Derby", "United Kingdom", "England", "GBR", 2651239},
	{"Swansea", "United Kingdom", "Wales", "GBR", 2636741},
	{"Southampton", "United Kingdom", "England", "GBR", 2637487},
	{"Salford", "United Kingdom", "England", "GBR", 2638078},
	{"Aberdeen", "United Kingdom", "Scotland", "GBR", 2657832},
	{"Westminster", "United Kingdom", "England", "GBR", 6695171},
	{"Portsmouth", "United Kingdom", "England", "GBR", 2640894},
	{"York", "United Kingdom", "England", "GBR", 2633352},
	{"Peterborough", "United Kingdom", "England", "GBR", 2640327},
	{"Dundee", "United Kingdom", "Scotland", "GBR", 2650752},
	{"Lancaster", "United Kingdom", "England", "GBR", 2644972},
	{"Oxford", "United Kingdom", "England", "GBR", 2640729},
	{"Newport", "United Kingdom", "Wales", "GBR", 2641633},
	{"Preston", "United Kingdom", "England", "GBR", 2640261},
	{"St Albans", "United Kingdom", "England", "GBR", 2637535},
	{"Norwich", "United Kingdom", "England", "GBR", 2641179},
	{"Cambridge", "United Kingdom", "England", "GBR", 2653941},
	{"Exeter", "United Kingdom", "England", "GBR", 2649808},

	// Poland - 30 cities
	{"Warszawa", "Poland", "Masovian Voivodeship", "POL", 756135},
	{"Kraków", "Poland", "Lesser Poland Voivodeship", "POL", 3094802},
	{"Łódź", "Poland", "Łódź Voivodeship", "POL", 3093133},
	{"Wrocław", "Poland", "Lower Silesian Voivodeship", "POL", 3081368},
	{"Poznań", "Poland", "Greater Poland Voivodeship", "POL", 3088171},
	{"Gdańsk", "Poland", "Pomeranian Voivodeship", "POL", 3099434},
	{"Szczecin", "Poland", "West Pomeranian Voivodeship", "POL", 3083829},
	{"Bydgoszcz", "Poland", "Kuyavian-Pomeranian Voivodeship", "POL", 3103472},
	{"Lublin", "Poland", "Lublin Voivodeship", "POL", 765876},
	{"Katowice", "Poland", "Silesian Voivodeship", "POL", 3096472},
	{"Białystok", "Poland", "Podlaskie Voivodeship", "POL", 776069},
	{"Gdynia", "Poland", "Pomeranian Voivodeship", "POL", 3099230},
	{"Częstochowa", "Poland", "Silesian Voivodeship", "POL", 3103386},
	{"Radom", "Poland", "Masovian Voivodeship", "POL", 759895},
	{"Sosnowiec", "Poland", "Silesian Voivodeship", "POL", 3084476},
	{"Toruń", "Poland", "Kuyavian-Pomeranian Voivodeship", "POL", 3083492},
	{"Kielce", "Poland", "Świętokrzyskie Voivodeship", "POL", 3096756},
	{"Rzeszów", "Poland", "Subcarpathian Voivodeship", "POL", 759354},
	{"Gliwice", "Poland", "Silesian Voivodeship", "POL", 3100206},
	{"Zabrze", "Poland", "Silesian Voivodeship", "POL", 3080803},
	{"Olsztyn", "Poland", "Warmian-Masurian Voivodeship", "POL", 762490},
	{"Bielsko-Biała", "Poland", "Silesian Voivodeship", "POL", 3103406},
	{"Bytom", "Poland", "Silesian Voivodeship", "POL", 3103450},
	{"Zielona Góra", "Poland", "Lubusz Voivodeship", "POL", 3080167},
	{"Rybnik", "Poland", "Silesian Voivodeship", "POL", 3085100},
	{"Ruda Śląska", "Poland", "Silesian Voivodeship", "POL", 3085249},
	{"Tychy", "Poland", "Silesian Voivodeship", "POL", 3082485},
	{"Opole", "Poland", "Opole Voivodeship", "POL", 3090048},
	{"Elbląg", "Poland", "Warmian-Masurian Voivodeship", "POL", 3100929},
	{"Płock", "Poland", "Masovian Voivodeship", "POL", 763966},

	// Portugal - 20 cities
	{"Lisboa", "Portugal", "Lisboa", "PRT", 2267057},
	{"Porto", "Portugal", "Porto", "PRT", 2735943},
	{"Vila Nova de Gaia", "Portugal", "Porto", "PRT", 2732265},
	{"Braga", "Portugal", "Braga", "PRT", 2742611},
	{"Funchal", "Portugal", "Madeira", "PRT", 2270385},
	{"Amadora", "Portugal", "Lisboa", "PRT", 2272188},
	{"Coimbra", "Portugal", "Coimbra", "PRT", 2740637},
	{"Setúbal", "Portugal", "Setúbal", "PRT", 2723833},
	{"Almada", "Portugal", "Setúbal", "PRT", 2270485},
	{"Agualva-Cacém", "Portugal", "Lisboa", "PRT", 8010530},
	{"Queluz", "Portugal", "Lisboa", "PRT", 2263855},
	{"Viseu", "Portugal", "Viseu", "PRT", 2732053},
	{"Guimarães", "Portugal", "Braga", "PRT", 2736234},
	{"Aveiro", "Portugal", "Aveiro", "PRT", 2742611},
	{"Évora", "Portugal", "Évora", "PRT", 2268339},
	{"Leiria", "Portugal", "Leiria", "PRT", 2266893},
	{"Faro", "Portugal", "Faro", "PRT", 2268339},
	{"Barreiro", "Portugal", "Setúbal", "PRT", 2271707},
	{"Matosinhos", "Portugal", "Porto", "PRT", 2736207},
	{"Loures", "Portugal", "Lisboa", "PRT", 2267066},

	// Netherlands - 20 cities
	{"Amsterdam", "Netherlands", "North Holland", "NLD", 2759794},
	{"Rotterdam", "Netherlands", "South Holland", "NLD", 2747891},
	{"Den Haag", "Netherlands", "South Holland", "NLD", 2747373},
	{"Utrecht", "Netherlands", "Utrecht", "NLD", 2745912},
	{"Eindhoven", "Netherlands", "North Brabant", "NLD", 2756253},
	{"Groningen", "Netherlands", "Groningen", "NLD", 2755251},
	{"Tilburg", "Netherlands", "North Brabant", "NLD", 2750053},
	{"Almere", "Netherlands", "Flevoland", "NLD", 3772031},
	{"Breda", "Netherlands", "North Brabant", "NLD", 2758727},
	{"Nijmegen", "Netherlands", "Gelderland", "NLD", 2750012},
	{"Enschede", "Netherlands", "Overijssel", "NLD", 2756429},
	{"Haarlem", "Netherlands", "North Holland", "NLD", 2755003},
	{"Arnhem", "Netherlands", "Gelderland", "NLD", 2759706},
	{"Zaanstad", "Netherlands", "North Holland", "NLD", 2744768},
	{"Amersfoort", "Netherlands", "Utrecht", "NLD", 2759660},
	{"Apeldoorn", "Netherlands", "Gelderland", "NLD", 2759660},
	{"Dordrecht", "Netherlands", "South Holland", "NLD", 2756964},
	{"Leiden", "Netherlands", "South Holland", "NLD", 2751773},
	{"Haarlemmermeer", "Netherlands", "North Holland", "NLD", 2754652},
	{"Zoetermeer", "Netherlands", "South Holland", "NLD", 2743562},

	// Belgium - 20 cities
	{"Brussel", "Belgium", "Brussels Capital Region", "BEL", 2800866},
	{"Antwerpen", "Belgium", "Flemish Region", "BEL", 2803138},
	{"Gent", "Belgium", "Flemish Region", "BEL", 2797656},
	{"Charleroi", "Belgium", "Walloon Region", "BEL", 2800481},
	{"Liège", "Belgium", "Walloon Region", "BEL", 2792482},
	{"Bruges", "Belgium", "Flemish Region", "BEL", 2800688},
	{"Namur", "Belgium", "Walloon Region", "BEL", 2790079},
	{"Leuven", "Belgium", "Flemish Region", "BEL", 2792482},
	{"Mons", "Belgium", "Walloon Region", "BEL", 2790068},
	{"Aalst", "Belgium", "Flemish Region", "BEL", 2804430},
	{"Mechelen", "Belgium", "Flemish Region", "BEL", 2790079},
	{"La Louvière", "Belgium", "Walloon Region", "BEL", 2792482},
	{"Kortrijk", "Belgium", "Flemish Region", "BEL", 2793564},
	{"Hasselt", "Belgium", "Flemish Region", "BEL", 2797524},
	{"Genk", "Belgium", "Flemish Region", "BEL", 2797656},
	{"Sint-Niklaas", "Belgium", "Flemish Region", "BEL", 2786901},
	{"Tournai", "Belgium", "Walloon Region", "BEL", 2789524},
	{"Ostende", "Belgium", "Flemish Region", "BEL", 2789524},
	{"Roeselare", "Belgium", "Flemish Region", "BEL", 2788868},
	{"Mouscron", "Belgium", "Walloon Region", "BEL", 2789524},

	// Sweden - 20 cities
	{"Stockholm", "Sweden", "Stockholm County", "SWE", 2673730},
	{"Göteborg", "Sweden", "Västra Götaland County", "SWE", 2711537},
	{"Malmö", "Sweden", "Skåne County", "SWE", 2692969},
	{"Uppsala", "Sweden", "Uppsala County", "SWE", 2666199},
	{"Västerås", "Sweden", "Västmanland County", "SWE", 2664454},
	{"Örebro", "Sweden", "Örebro County", "SWE", 2684578},
	{"Linköping", "Sweden", "Östergötland County", "SWE", 2693678},
	{"Helsingborg", "Sweden", "Skåne County", "SWE", 2706751},
	{"Jönköping", "Sweden", "Jönköping County", "SWE", 2701193},
	{"Norrköping", "Sweden", "Östergötland County", "SWE", 2684724},
	{"Lund", "Sweden", "Skåne County", "SWE", 2693034},
	{"Umeå", "Sweden", "Västernorrland County", "SWE", 602628},
	{"Gävle", "Sweden", "Gävleborg County", "SWE", 2713582},
	{"Borås", "Sweden", "Västra Götaland County", "SWE", 2720029},
	{"Södertälje", "Sweden", "Stockholm County", "SWE", 2676099},
	{"Eskilstuna", "Sweden", "Södermanland County", "SWE", 2721299},
	{"Halmstad", "Sweden", "Halland County", "SWE", 2706892},
	{"Växjö", "Sweden", "Kronoberg County", "SWE", 2663197},
	{"Karlstad", "Sweden", "Värmland County", "SWE", 2704400},
	{"Sundsvall", "Sweden", "Västernorrland County", "SWE", 2674484},

	// Romania - 20 cities
	{"București", "Romania", "Ilfov County", "ROU", 683506},
	{"Cluj-Napoca", "Romania", "Cluj County", "ROU", 681290},
	{"Timișoara", "Romania", "Timiș County", "ROU", 665087},
	{"Iași", "Romania", "Iași County", "ROU", 675095},
	{"Constanța", "Romania", "Constanța County", "ROU", 681290},
	{"Craiova", "Romania", "Dolj County", "ROU", 681290},
	{"Brașov", "Romania", "Brașov County", "ROU", 681879},
	{"Galați", "Romania", "Galați County", "ROU", 681290},
	{"Ploiești", "Romania", "Prahova County", "ROU", 670989},
	{"Oradea", "Romania", "Bihor County", "ROU", 671057},
	{"Braila", "Romania", "Brăila County", "ROU", 681290},
	{"Arad", "Romania", "Arad County", "ROU", 681290},
	{"Pitești", "Romania", "Argeș County", "ROU", 670989},
	{"Bacău", "Romania", "Bacău County", "ROU", 681290},
	{"Deva", "Romania", "Hunedoara County", "ROU", 681290},
	{"Sibiu", "Romania", "Sibiu County", "ROU", 667268},
	{"Baia Mare", "Romania", "Maramureș County", "ROU", 681290},
	{"Buzău", "Romania", "Buzău County", "ROU", 681290},
	{"Botoșani", "Romania", "Botoșani County", "ROU", 681290},
	{"Satu Mare", "Romania", "Satu Mare County", "ROU", 681290},

	// Czech Republic - 15 cities
	{"Praha", "Czech Republic", "Hlavní město Praha", "CZE", 3067696},
	{"Brno", "Czech Republic", "South Moravian Region", "CZE", 3078610},
	{"Ostrava", "Czech Republic", "Moravian-Silesian Region", "CZE", 3068799},
	{"Plzeň", "Czech Republic", "Plzeň Region", "CZE", 3068927},
	{"Liberec", "Czech Republic", "Liberec Region", "CZE", 3071961},
	{"Olomouc", "Czech Republic", "Olomouc Region", "CZE", 3069011},
	{"Ústí nad Labem", "Czech Republic", "Ústí nad Labem Region", "CZE", 3064030},
	{"České Budějovice", "Czech Republic", "South Bohemian Region", "CZE", 3078610},
	{"Hradec Králové", "Czech Republic", "Hradec Králové Region", "CZE", 3076058},
	{"Pardubice", "Czech Republic", "Pardubice Region", "CZE", 3068927},
	{"Zlín", "Czech Republic", "Zlín Region", "CZE", 3060972},
	{"Opava", "Czech Republic", "Moravian-Silesian Region", "CZE", 3069011},
	{"Most", "Czech Republic", "Ústí nad Labem Region", "CZE", 3064030},
	{"Karviná", "Czech Republic", "Moravian-Silesian Region", "CZE", 3078610},
	{"Kladno", "Czech Republic", "Central Bohemian Region", "CZE", 3076058},

	// Greece - 15 cities
	{"Athinai", "Greece", "Attica", "GRC", 264371},
	{"Thessaloniki", "Greece", "Central Macedonia", "GRC", 734077},
	{"Patra", "Greece", "Western Greece", "GRC", 261604},
	{"Peristeri", "Greece", "Attica", "GRC", 264371},
	{"Heraklion", "Greece", "Crete", "GRC", 8133976},
	{"Larissa", "Greece", "Thessaly", "GRC", 264371},
	{"Volos", "Greece", "Thessaly", "GRC", 264371},
	{"Ioannina", "Greece", "Epirus", "GRC", 264371},
	{"Trikala", "Greece", "Thessaly", "GRC", 264371},
	{"Chalkida", "Greece", "Central Greece", "GRC", 264371},
	{"Serres", "Greece", "Central Macedonia", "GRC", 264371},
	{"Alexandroupolis", "Greece", "Eastern Macedonia and Thrace", "GRC", 264371},
	{"Katerini", "Greece", "Central Macedonia", "GRC", 264371},
	{"Kavala", "Greece", "Eastern Macedonia and Thrace", "GRC", 264371},
	{"Lamia", "Greece", "Central Greece", "GRC", 264371},

	// Hungary - 15 cities
	{"Budapest", "Hungary", "Budapest", "HUN", 3054643},
	{"Debrecen", "Hungary", "Hajdú-Bihar County", "HUN", 721472},
	{"Miskolc", "Hungary", "Borsod-Abaúj-Zemplén County", "HUN", 717582},
	{"Szeged", "Hungary", "Csongrád-Csanád County", "HUN", 715429},
	{"Pécs", "Hungary", "Baranya County", "HUN", 3046526},
	{"Győr", "Hungary", "Győr-Moson-Sopron County", "HUN", 3053163},
	{"Nyíregyháza", "Hungary", "Szabolcs-Szatmár-Bereg County", "HUN", 717582},
	{"Kecskemét", "Hungary", "Bács-Kiskun County", "HUN", 3047233},
	{"Székesfehérvár", "Hungary", "Fejér County", "HUN", 3045020},
	{"Szombathely", "Hungary", "Vas County", "HUN", 3043507},
	{"Érd", "Hungary", "Pest County", "HUN", 3054643},
	{"Tatabánya", "Hungary", "Komárom-Esztergom County", "HUN", 3054643},
	{"Sopron", "Hungary", "Győr-Moson-Sopron County", "HUN", 3053163},
	{"Kaposvár", "Hungary", "Somogy County", "HUN", 3054643},
	{"Eger", "Hungary", "Heves County", "HUN", 3054643},

	// Austria - 10 cities
	{"Wien", "Austria", "Vienna", "AUT", 2761369},
	{"Graz", "Austria", "Styria", "AUT", 2778067},
	{"Linz", "Austria", "Upper Austria", "AUT", 2772400},
	{"Salzburg", "Austria", "Salzburg", "AUT", 2766824},
	{"Innsbruck", "Austria", "Tyrol", "AUT", 2775220},
	{"Klagenfurt", "Austria", "Carinthia", "AUT", 2774686},
	{"Villach", "Austria", "Carinthia", "AUT", 2762338},
	{"Wels", "Austria", "Upper Austria", "AUT", 2760676},
	{"Sankt Pölten", "Austria", "Lower Austria", "AUT", 2766429},
	{"Dornbirn", "Austria", "Vorarlberg", "AUT", 2781363},

	// Switzerland - 10 cities
	{"Zürich", "Switzerland", "Canton of Zürich", "CHE", 2657896},
	{"Genève", "Switzerland", "Canton of Geneva", "CHE", 2660646},
	{"Basel", "Switzerland", "Canton of Basel-City", "CHE", 2661604},
	{"Bern", "Switzerland", "Canton of Bern", "CHE", 2661552},
	{"Lausanne", "Switzerland", "Canton of Vaud", "CHE", 2659994},
	{"Winterthur", "Switzerland", "Canton of Zürich", "CHE", 2657895},
	{"Lucerne", "Switzerland", "Canton of Lucerne", "CHE", 2659811},
	{"St. Gallen", "Switzerland", "Canton of St. Gallen", "CHE", 2658822},
	{"Lugano", "Switzerland", "Canton of Ticino", "CHE", 2659854},
	{"Biel", "Switzerland", "Canton of Bern", "CHE", 2661604},

	// Denmark - 4 cities
	{"Copenhagen", "Denmark", "Capital Region", "DNK", 2618425},
	{"Aarhus", "Denmark", "Central Jutland Region", "DNK", 2624652},
	{"Odense", "Denmark", "Southern Denmark Region", "DNK", 2615876},
	{"Aalborg", "Denmark", "North Jutland Region", "DNK", 2624886},

	// Finland - 4 cities
	{"Helsinki", "Finland", "Uusimaa", "FIN", 658225},
	{"Espoo", "Finland", "Uusimaa", "FIN", 660879},
	{"Tampere", "Finland", "Pirkanmaa", "FIN", 634963},
	{"Vantaa", "Finland", "Uusimaa", "FIN", 658225},

	// Norway - 4 cities
	{"Oslo", "Norway", "Oslo", "NOR", 3143244},
	{"Bergen", "Norway", "Vestland", "NOR", 3161732},
	{"Trondheim", "Norway", "Trøndelag", "NOR", 3133880},
	{"Stavanger", "Norway", "Rogaland", "NOR", 3137115},

	// Ireland - 4 cities
	{"Dublin", "Ireland", "Leinster", "IRL", 2964574},
	{"Cork", "Ireland", "Munster", "IRL", 2965140},
	{"Limerick", "Ireland", "Munster", "IRL", 2963046},
	{"Galway", "Ireland", "Connacht", "IRL", 2964179},

	// Croatia - 4 cities
	{"Zagreb", "Croatia", "City of Zagreb", "HRV", 3186886},
	{"Split", "Croatia", "Split-Dalmatia County", "HRV", 3190261},
	{"Rijeka", "Croatia", "Primorje-Gorski Kotar County", "HRV", 3191648},
	{"Osijek", "Croatia", "Osijek-Baranja County", "HRV", 3193935},

	// Slovakia - 4 cities
	{"Bratislava", "Slovakia", "Bratislava Region", "SVK", 3060972},
	{"Košice", "Slovakia", "Košice Region", "SVK", 724443},
	{"Prešov", "Slovakia", "Prešov Region", "SVK", 724443},
	{"Nitra", "Slovakia", "Nitra Region", "SVK", 3060972},

	// Bulgaria - 4 cities
	{"Sofia", "Bulgaria", "Sofia City Province", "BGR", 727011},
	{"Plovdiv", "Bulgaria", "Plovdiv Province", "BGR", 728193},
	{"Varna", "Bulgaria", "Varna Province", "BGR", 726050},
	{"Burgas", "Bulgaria", "Burgas Province", "BGR", 731549},

	// Serbia - 4 cities
	{"Belgrade", "Serbia", "Belgrade", "SRB", 792680},
	{"Novi Sad", "Serbia", "South Bačka District", "SRB", 783726},
	{"Niš", "Serbia", "Nišava District", "SRB", 785842},
	{"Subotica", "Serbia", "North Bačka District", "SRB", 784235},
}

var dgStreets = []dgStreet{
	{"Via Roma"},
	{"Via Garibaldi"},
	{"Corso Italia"},
	{"Via Mazzini"},
	{"Piazza Duomo"},
	{"Viale della Repubblica"},
	{"Vicolo delle Rose"},
	{"Via dei Mille"},
	{"Corso Vittorio Emanuele"},
	{"Via Nazionale"},
	{"Via Cavour"},
	{"Via Verdi"},
	{"Corso Umberto"},
	{"Via Dante"},
	{"Piazza della Libertà"},
	{"Via XX Settembre"},
	{"Viale Europa"},
	{"Via della Pace"},
	{"Corso Matteotti"},
	{"Via Torino"},
	{"Via Venezia"},
	{"Piazza San Marco"},
	{"Vicolo Stretto"},
	{"Via dei Fiori"},
	{"Corso Garibaldi"},
	{"Rue de la Paix"},
	{"Avenue des Champs-Élysées"},
	{"Boulevard Saint-Michel"},
	{"Rue Victor Hugo"},
	{"Place de la République"},
	{"Allée des Roses"},
	{"Avenue de la Gare"},
	{"Rue du Commerce"},
	{"Boulevard Haussmann"},
	{"Place du Marché"},
	{"Rue de Rivoli"},
	{"Boulevard des Capucines"},
	{"Avenue Montaigne"},
	{"Rue Lafayette"},
	{"Rue Faubourg Saint-Antoine"},
	{"Allée des Platanes"},
	{"Avenue de la Liberté"},
	{"Rue des Fleurs"},
	{"Boulevard de la Mer"},
	{"Rue du Port"},
	{"Hauptstraße"},
	{"Bahnhofstraße"},
	{"Kirchgasse"},
	{"Marktplatz"},
	{"Rosenallee"},
	{"Gartenweg"},
	{"Schlossberg"},
	{"Bergstraße"},
	{"Lindenstraße"},
	{"Friedrichstraße"},
	{"Wilhelmstraße"},
	{"Goethestraße"},
	{"Schillerstraße"},
	{"Mozartstraße"},
	{"Bismarckstraße"},
	{"Kaiserstraße"},
	{"Ringstraße"},
	{"Parkweg"},
	{"Waldstraße"},
	{"Fichtenweg"},
	{"Calle Mayor"},
	{"Paseo de Gracia"},
	{"Avenida de la Constitución"},
	{"Calle de la Paz"},
	{"Plaza Mayor"},
	{"Camino Real"},
	{"Avenida del Mar"},
	{"Calle Nueva"},
	{"Gran Vía"},
	{"Paseo del Prado"},
	{"Calle Ancha"},
	{"Avenida de España"},
	{"Plaza de la Iglesia"},
	{"Calle Colón"},
	{"Rambla de les Flors"},
	{"High Street"},
	{"King's Road"},
	{"Oxford Street"},
	{"Park Lane"},
	{"Victoria Road"},
	{"Church Lane"},
	{"Manor Close"},
	{"Green Way"},
	{"Castle Street"},
	{"Market Square"},
	{"Bridge Road"},
	{"Mill Lane"},
	{"Station Road"},
	{"Queens Avenue"},
	{"London Road"},
	{"ul. Marszałkowska"},
	{"ul. Krakowska"},
	{"Aleja Róż"},
	{"ul. Lipowa"},
	{"ul. Piłsudskiego"},
	{"Praça do Comércio"},
	{"Rua Augusta"},
	{"Avenida da Liberdade"},
	{"Rua do Ouro"},
	{"Praça do Rossio"},
	{"Keizersgracht"},
	{"Herengracht"},
	{"Vondelstraat"},
	{"Prinsengracht"},
	{"Leidseplein"},
	{"Andrássy út"},
	{"Váci utca"},
	{"Rákóczi út"},
	{"Király utca"},
	{"Dohány utca"},
	{"Nám. Míru"},
	{"Václavské náměstí"},
	{"Náměstí Republiky"},
	{"Wenceslas Square"},
	{"Μεγάλης Αλεξάνδρου"},
	{"Ερμού"},
	{"Βενιζέλου"},
	{"Πανεπιστημίου"},
	{"Strandvejen"},
	{"Bredgade"},
	{"Esplanaden"},
	{"Strøget"},
	{"Mannerheimintie"},
	{"Aleksanterinkatu"},
	{"Esplanadin puisto"},
	{"Karl Johans gate"},
	{"Drottninggatan"},
	{"Kungsgatan"},
	{"Strandgatan"},
	{"Strada Unirii"},
	{"Bulevardul Revoluției"},
	{"Calea Victoriei"},
	{"Strada Republicii"},
	{"Bulevardul Independenței"},
}

var dgStreetNames []string

func init() {
	dgStreetNames = make([]string, len(dgStreets))
	for i, s := range dgStreets {
		dgStreetNames[i] = s.streetname
	}
}

var dgFirstNamesMale = []string{
	// Italian
	"Alessandro", "Marco", "Luca", "Lorenzo", "Matteo", "Francesco", "Andrea", "Giovanni",
	"Stefano", "Davide", "Fabio", "Roberto", "Antonio", "Giuseppe", "Riccardo", "Simone",
	"Daniele", "Emanuele", "Nicola", "Vincenzo", "Pietro", "Paolo", "Luigi", "Massimo", "Enrico",
	// French
	"Pierre", "Jean", "Michel", "André", "Philippe", "Nicolas", "Antoine", "Julien",
	"Thomas", "Christophe", "Laurent", "François", "Sébastien", "Guillaume", "Alexis",
	"Romain", "Maxime", "Baptiste", "Hugo", "Théo",
	// German
	"Hans", "Klaus", "Werner", "Dieter", "Günter", "Wolfgang", "Helmut", "Karl",
	"Peter", "Michael", "Andreas", "Stefan", "Christian", "Daniel", "Markus",
	"Sebastian", "Tobias", "Felix", "Maximilian", "Florian",
	// Spanish
	"Carlos", "Antonio", "Manuel", "Francisco", "David", "José", "Miguel", "Pedro",
	"Juan", "Alejandro", "Jorge", "Alberto", "Sergio", "Javier", "Luis",
	"Pablo", "Rafael", "Ramón", "Andrés", "Tomás",
	// English
	"James", "John", "Robert", "William", "Richard", "Joseph", "Charles",
	"Christopher", "Matthew", "Anthony", "Mark", "Andrew", "Steven", "Joshua", "Kenneth", "Paul",
	// Polish
	"Adam", "Piotr", "Marek", "Krzysztof", "Tomasz", "Michał", "Andrzej", "Grzegorz",
	"Jakub", "Marcin", "Łukasz", "Jan", "Paweł", "Bartosz", "Rafał",
	// Greek
	"Nikos", "Dimitrios", "Georgios", "Konstantinos", "Yannis",
	// Hungarian
	"István", "László", "Péter", "Zoltán", "Gábor",
	// Czech
	"Pavel", "Jakub", "Ondřej", "Marek", "Tomáš",
	// Romanian
	"Ion", "Andrei", "Mihai", "Bogdan", "Florin",
	// Nordic
	"Magnus", "Lars", "Erik", "Björn", "Sven", "Olaf", "Henrik",
}

var dgFirstNamesFemale = []string{
	// Italian
	"Sofia", "Emma", "Giulia", "Aurora", "Alice", "Ginevra", "Beatrice", "Martina",
	"Sara", "Laura", "Chiara", "Federica", "Valentina", "Elisa", "Francesca",
	"Elena", "Silvia", "Claudia", "Roberta", "Monica",
	// French
	"Marie", "Camille", "Sophie", "Lucie", "Chloé", "Léa", "Manon", "Élodie",
	"Pauline", "Juliette", "Julie", "Audrey", "Margot", "Mathilde", "Anaïs",
	"Charlotte", "Emilie", "Céline", "Laure", "Nathalie",
	// German
	"Anna", "Maria", "Lena", "Julia", "Hannah", "Sarah", "Lisa", "Katharina",
	"Christina", "Sandra", "Nicole", "Sabine", "Claudia", "Petra", "Monika",
	"Birgit", "Stefanie", "Franziska", "Karin", "Renate",
	// Spanish
	"María", "Carmen", "Isabel", "Ana", "Patricia", "Cristina", "Marta",
	"Rosa", "Dolores", "Teresa", "Pilar", "Nuria", "Andrea", "Raquel",
	"Paula", "Beatriz", "Sonia", "Leticia", "Mónica", "Inmaculada",
	// English
	"Mary", "Jennifer", "Patricia", "Linda", "Barbara", "Elizabeth", "Susan",
	"Jessica", "Sarah", "Karen", "Lisa", "Nancy", "Betty", "Margaret",
	"Sandra", "Ashley", "Emily", "Donna", "Michelle", "Carol",
	// Polish
	"Anna", "Katarzyna", "Małgorzata", "Agnieszka", "Barbara", "Ewa", "Zofia",
	"Monika", "Joanna", "Natalia", "Karolina", "Magdalena", "Paulina", "Aleksandra", "Marta",
	// Greek
	"Eleni", "Anastasia", "Dimitra", "Katerina", "Stavroula",
	// Hungarian
	"Erzsébet", "Katalin", "Judit", "Ágnes", "Zsuzsanna",
	// Czech
	"Ivana", "Petra", "Lucie", "Jana", "Martina",
	// Romanian
	"Ioana", "Ana", "Elena", "Cristina", "Mihaela",
	// Nordic
	"Ingrid", "Astrid", "Sigrid", "Helga", "Freya", "Britta", "Solveig",
}

var dgMaleNames = dgFirstNamesMale
var dgFemaleNames = dgFirstNamesFemale

var dgLastNamesList = []string{
	// Italian (40)
	"Rossi", "Ferrari", "Bianchi", "Esposito", "Romano", "Colombo", "Ricci", "Marino",
	"Greco", "Bruno", "Gallo", "Conti", "De Luca", "Mancini", "Costa", "Giordano",
	"Rizzo", "Lombardi", "Moretti", "Barbieri", "Fontana", "Santoro", "Marini", "Rinaldi",
	"Caruso", "Ferretti", "Ferrara", "Gatti", "Cattaneo", "Pellegrini",
	"Palumbo", "Testa", "Villa", "Bianco", "Ruggiero", "Valentini", "Guerra", "Martini",
	"Longo", "Coppola",
	// French (40)
	"Martin", "Bernard", "Thomas", "Petit", "Robert", "Richard", "Durand", "Dubois",
	"Moreau", "Simon", "Laurent", "Lefebvre", "Michel", "Garcia", "David",
	"Bertrand", "Roux", "Vincent", "Fournier", "Morin", "Girard", "André", "Lefevre",
	"Mercier", "Dupont", "Lambert", "Bonnet", "François", "Martinez", "Legrand",
	"Garnier", "Faure", "Rousseau", "Blanc", "Guerin", "Muller", "Henry", "Roussel",
	"Nicolas", "Perrin",
	// German (40)
	"Müller", "Schmidt", "Schneider", "Fischer", "Weber", "Meyer", "Wagner", "Becker",
	"Schulz", "Hoffmann", "Schäfer", "Koch", "Bauer", "Richter", "Klein",
	"Wolf", "Schröder", "Neumann", "Schwarz", "Zimmermann", "Braun", "Krüger", "Hofmann",
	"Hartmann", "Lange", "Schmitt", "Werner", "Schmitz", "Krause", "Meier",
	"Lehmann", "Schmid", "Schulze", "Maier", "Köhler", "Herrmann", "König", "Walter",
	"Mayer", "Huber",
	// Spanish (30)
	"García", "Rodríguez", "González", "Fernández", "López", "Martínez", "Sánchez",
	"Pérez", "Gómez", "Martín", "Jiménez", "Ruiz", "Hernández", "Díaz", "Moreno",
	"Álvarez", "Romero", "Alonso", "Gutiérrez", "Navarro", "Torres", "Domínguez",
	"Ramos", "Gil", "Ramírez", "Serrano", "Blanco", "Molina", "Morales", "Suárez",
	// Polish (20)
	"Nowak", "Kowalski", "Wiśniewski", "Wójcik", "Kowalczyk", "Kamiński", "Lewandowski",
	"Zieliński", "Woźniak", "Szymański", "Dąbrowski", "Kozłowski", "Jankowski", "Mazur",
	"Wojciechowski", "Kwiatkowski", "Krawczyk", "Kaczmarek", "Piotrowski", "Grabowski",
	// English (20)
	"Smith", "Jones", "Williams", "Taylor", "Brown", "Davies", "Evans", "Wilson",
	"Thomas", "Roberts", "Johnson", "Lewis", "Walker", "Robinson", "Wood",
	"Thompson", "White", "Watson", "Jackson", "Harris",
	// Others (10)
	"Nagy", "Kovács", "Novák", "Dvořák", "Popescu", "Ionescu",
	"Andersen", "Hansen", "Johansson", "Andersson",
}

var dgTitles = []dgTitle{
	{"Mr", 0, 1, 0, 1, 1},
	{"Mrs", 0, 0, 1, 2, 2},
	{"Ms", 0, 0, 1, 3, 3},
	{"Dr", 1, 0, 0, 4, 4},
	{"Prof", 1, 0, 0, 5, 5},
	{"Ing", 1, 0, 0, 6, 6},
	{"Avv", 1, 0, 0, 7, 7},
}

var dgPopulation = []dgPopulationRow{
	{"Germany", "DEU", "Population, total", "SP.POP.TOTL", 83166711, 83240525, 83695430},
	{"France", "FRA", "Population, total", "SP.POP.TOTL", 67028048, 67422241, 67874422},
	{"United Kingdom", "GBR", "Population, total", "SP.POP.TOTL", 66836327, 67326569, 67326569},
	{"Italy", "ITA", "Population, total", "SP.POP.TOTL", 59729081, 59554023, 59257566},
	{"Spain", "ESP", "Population, total", "SP.POP.TOTL", 46937060, 47351567, 47415750},
	{"Poland", "POL", "Population, total", "SP.POP.TOTL", 37887768, 37840001, 37747124},
	{"Romania", "ROU", "Population, total", "SP.POP.TOTL", 19364557, 19116040, 18883955},
	{"Netherlands", "NLD", "Population, total", "SP.POP.TOTL", 17282163, 17441139, 17533044},
	{"Belgium", "BEL", "Population, total", "SP.POP.TOTL", 11455519, 11589616, 11554767},
	{"Czech Republic", "CZE", "Population, total", "SP.POP.TOTL", 10669709, 10693939, 10827529},
	{"Sweden", "SWE", "Population, total", "SP.POP.TOTL", 10278887, 10327589, 10379295},
	{"Greece", "GRC", "Population, total", "SP.POP.TOTL", 10718565, 10682547, 10664568},
	{"Portugal", "PRT", "Population, total", "SP.POP.TOTL", 10226187, 10305564, 10290103},
	{"Hungary", "HUN", "Population, total", "SP.POP.TOTL", 9684679, 9730772, 9689010},
	{"Austria", "AUT", "Population, total", "SP.POP.TOTL", 8879920, 9006398, 9056478},
	{"Switzerland", "CHE", "Population, total", "SP.POP.TOTL", 8544527, 8654622, 8738791},
	{"Bulgaria", "BGR", "Population, total", "SP.POP.TOTL", 6975761, 6916548, 6889511},
	{"Denmark", "DNK", "Population, total", "SP.POP.TOTL", 5806081, 5822763, 5856010},
	{"Finland", "FIN", "Population, total", "SP.POP.TOTL", 5516574, 5525292, 5533062},
	{"Slovakia", "SVK", "Population, total", "SP.POP.TOTL", 5450421, 5456362, 5449270},
	{"Norway", "NOR", "Population, total", "SP.POP.TOTL", 5328212, 5367580, 5403021},
	{"Ireland", "IRL", "Population, total", "SP.POP.TOTL", 4921500, 4977400, 5011500},
	{"Croatia", "HRV", "Population, total", "SP.POP.TOTL", 4076246, 3871833, 3908135},
	{"Lithuania", "LTU", "Population, total", "SP.POP.TOTL", 2795680, 2795284, 2786651},
	{"Latvia", "LVA", "Population, total", "SP.POP.TOTL", 1913822, 1895400, 1883008},
	{"Estonia", "EST", "Population, total", "SP.POP.TOTL", 1325648, 1329660, 1330068},
	{"Luxembourg", "LUX", "Population, total", "SP.POP.TOTL", 619896, 632275, 645397},
	{"Malta", "MLT", "Population, total", "SP.POP.TOTL", 441543, 520971, 519562},
	{"Iceland", "ISL", "Population, total", "SP.POP.TOTL", 360390, 364260, 368792},
	{"Montenegro", "MNE", "Population, total", "SP.POP.TOTL", 622781, 619211, 616428},
}
